apiVersion: v1
kind: PersistentVolume
metadata:
  name: placide-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: placide-mysql-pvc
  namespace: placide-ns
  labels:
    app: placide-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500M