apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ingress-microservices-config-service
  labels:
    app: k8s-ingress-microservices-config-service
  namespace: placide-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-ingress-microservices-config-service
  template:
    metadata:
      name: k8s-ingress-microservices-config-service
      labels:
        app: k8s-ingress-microservices-config-service
    spec:
      serviceAccountName: placide-svc-account
      containers:
        - name: k8s-ingress-microservices-config-service
          image: placidenduwayo1/k8s-ingress-microservices-config-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8380
              name: conf-svc-port
          startupProbe:
            httpGet:
              port: conf-svc-port
              path: /ms-config-svc
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: conf-svc-port
              path: /ms-config-svc
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: conf-svc-port
              path: /ms-config-svc
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ingress-microservices-config-service
  labels:
    app: k8s-ingress-microservices-config-service
  namespace: placide-ns
spec:
  selector:
    app: k8s-ingress-microservices-config-service
  ports:
    - port: 8380
      protocol: TCP
      targetPort: 8380
      name: http
  type: ClusterIP
